include $(GOROOT)/src/Make.inc

GCIMPORTS=-I ../types/_obj

TARG=chunkymonkey/recipe
TARGDIR=../_obj
GCIMPORTS=-I ../_obj

GOFILES=\
		furnace_data.go \
		loader.go \
		recipe.go \

include $(GOROOT)/src/Make.pkg
