include $(GOROOT)/src/Make.inc

TARG=chunkymonkey/player
TARGDIR=../_obj
GCIMPORTS=-I ../_obj

GOFILES=\
		command.go \
		player.go \
		player_subscription.go \
		remote_inventory.go \
		shard_player_client.go \

include $(GOROOT)/src/Make.pkg
