include $(GOROOT)/src/Make.inc

TARG=chunkymonkey/shardserver
TARGDIR=../_obj
GCIMPORTS=-I ../_obj

GOFILES=\
		chunk.go \
		local_player_shard_client.go \
		local_shard_shard_client.go \
		localshardmgr.go \
		playerdata.go \
		shard.go \
		shardrequest.go \
		side.go \

include $(GOROOT)/src/Make.pkg
