include $(GOROOT)/src/Make.inc

GCIMPORTS=-I ../types/_obj

TARG=chunkymonkey/block
TARGDIR=../_obj
GCIMPORTS=-I ../_obj

GOFILES=\
		aspect.go \
		block_inventory.go \
		blocktype.go \
		blocktype_test.go \
		chest_aspect.go \
		furnace_aspect.go \
		inv_aspect.go \
		item_spawn.go \
		loader.go \
		loader_test.go \
		standard_aspect.go \
		todo_aspect.go \
		void_aspect.go \
		workbench_aspect.go \

include $(GOROOT)/src/Make.pkg
