include $(GOROOT)/src/Make.inc

TARG=chunkymonkey/chunkstore
TARGDIR=../_obj
GCIMPORTS=-I ../_obj

GOFILES=\
		alpha.go \
		beta.go \
		chunk_reader.go \
		chunkservice.go \
		store.go \

include $(GOROOT)/src/Make.pkg
