include $(GOROOT)/src/Make.inc

GCIMPORTS=-I ../types/_obj

TARG=chunkymonkey/inventory
TARGDIR=../_obj
GCIMPORTS=-I ../_obj

GOFILES=\
		chest.go \
		crafting.go \
		furnace.go \
		inventory.go \

include $(GOROOT)/src/Make.pkg
