# Build script generated by gb: http://go-gb.googlecode.com
# gb provides configuration-free building and distributing

echo "Build script generated by gb: http://go-gb.googlecode.com" 
if [ "$1" = "goinstall" ]; then
echo Running goinstall \

else
echo Building \
&& echo "(in pkg/chunkymonkey/types)" && cd pkg/chunkymonkey/types && make $1 && cd - > /dev/null \
&& echo "(in pkg/chunkymonkey/itemtype)" && cd pkg/chunkymonkey/itemtype && make $1 && cd - > /dev/null \
&& echo "(in pkg/chunkymonkey/proto)" && cd pkg/chunkymonkey/proto && make $1 && cd - > /dev/null \
&& echo "(in pkg/chunkymonkey/slot)" && cd pkg/chunkymonkey/slot && make $1 && cd - > /dev/null \
&& echo "(in pkg/chunkymonkey/recipe)" && cd pkg/chunkymonkey/recipe && make $1 && cd - > /dev/null \
&& echo "(in pkg/chunkymonkey/inventory)" && cd pkg/chunkymonkey/inventory && make $1 && cd - > /dev/null \
&& echo "(in pkg/chunkymonkey/physics)" && cd pkg/chunkymonkey/physics && make $1 && cd - > /dev/null \
&& echo "(in pkg/chunkymonkey/object)" && cd pkg/chunkymonkey/object && make $1 && cd - > /dev/null \
&& echo "(in pkg/chunkymonkey/item)" && cd pkg/chunkymonkey/item && make $1 && cd - > /dev/null \
&& echo "(in pkg/chunkymonkey/stub)" && cd pkg/chunkymonkey/stub && make $1 && cd - > /dev/null \
&& echo "(in pkg/chunkymonkey/block)" && cd pkg/chunkymonkey/block && make $1 && cd - > /dev/null \
&& echo "(in pkg/chunkymonkey/gamerules)" && cd pkg/chunkymonkey/gamerules && make $1 && cd - > /dev/null \
&& echo "(in pkg/chunkymonkey/window)" && cd pkg/chunkymonkey/window && make $1 && cd - > /dev/null \
&& echo "(in pkg/chunkymonkey/player)" && cd pkg/chunkymonkey/player && make $1 && cd - > /dev/null \
&& echo "(in pkg/chunkymonkey/nbt)" && cd pkg/chunkymonkey/nbt && make $1 && cd - > /dev/null \
&& echo "(in pkg/chunkymonkey/chunkstore)" && cd pkg/chunkymonkey/chunkstore && make $1 && cd - > /dev/null \
&& echo "(in pkg/chunkymonkey/worldstore)" && cd pkg/chunkymonkey/worldstore && make $1 && cd - > /dev/null \
&& echo "(in pkg/chunkymonkey/server_auth)" && cd pkg/chunkymonkey/server_auth && make $1 && cd - > /dev/null \
&& echo "(in pkg/chunkymonkey/record)" && cd pkg/chunkymonkey/record && make $1 && cd - > /dev/null \
&& echo "(in pkg/chunkymonkey/mob)" && cd pkg/chunkymonkey/mob && make $1 && cd - > /dev/null \
&& echo "(in pkg/chunkymonkey/logdebug)" && cd pkg/chunkymonkey/logdebug && make $1 && cd - > /dev/null \
&& echo "(in cmd/inspectlevel)" && cd cmd/inspectlevel && make $1 && cd - > /dev/null \
&& echo "(in cmd/intercept)" && cd cmd/intercept && make $1 && cd - > /dev/null \
&& echo "(in cmd/replay)" && cd cmd/replay && make $1 && cd - > /dev/null \
&& echo "(in pkg/chunkymonkey/entity)" && cd pkg/chunkymonkey/entity && make $1 && cd - > /dev/null \
&& echo "(in cmd/datatests)" && cd cmd/datatests && make $1 && cd - > /dev/null \
&& echo "(in pkg/chunkymonkey/shardserver)" && cd pkg/chunkymonkey/shardserver && make $1 && cd - > /dev/null \
&& echo "(in cmd/style)" && cd cmd/style && make $1 && cd - > /dev/null \
&& echo "(in cmd/dumpblockdefs)" && cd cmd/dumpblockdefs && make $1 && cd - > /dev/null \
&& echo "(in pkg/chunkymonkey)" && cd pkg/chunkymonkey && make $1 && cd - > /dev/null \
&& echo "(in cmd/chunkymonkey)" && cd cmd/chunkymonkey && make $1 && cd - > /dev/null \

fi

# The makefiles above are invoked in topological dependence order
